# Inspired by https://github.com/openfaas/faas/blob/master/.github/workflows/publish.yml
name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set TAG
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Publish ${{ matrix.svc }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            wkirk/busyboxhttpd:${{ env.TAG }}
            wkirk/busyboxhttpd:latest
